spring:
  profiles:
    active: debug
  mail:
    default-encoding: UTF-8
    username: fanneng@enn.cn
    password: G-AZH29Y
    host: smtp.exmail.qq.com
    spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
    port: 465
logging:
  config: classpath:logback-energy.xml

mybatis-plus:
      mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
      #config-location: classpath:/mybatis/mybatis-config.xml