spring:
  application:
    name: energy-provider-business
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.39.48.241:3306/uee?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: uee_prepare
    password: uee_prepare
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
  redis:
    host: 10.39.30.243
    port: 6379
    database: 0
    password: FNadmin1234
    timeout: 4000
    pool:
      max-active: 300
      min-idle: 10
      max-idle: 100
      max-wait: 6000
      test-on-create: false
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
  rabbitmq:
      host: 10.39.30.42
      port: 5672
      username: fnuser
      password: fnuser
      alarmQueue: fanneng-etsp-alarm-input-v1
      topicExchange: amq.topic


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-01-fnw-prod.topaas.enncloud.cn/eureka,http://eureka-02-fnw-prod.topaas.enncloud.cn/eureka,http://eureka-03-fnw-prod.topaas.enncloud.cn/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true     # 访问的路径变为IP地址
    #hostname: etsp-provider-rmi-fnw-dev.topaas.enncloud.cn
    #non-secure-port: 80


server:
  port: 8081

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 6000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000



opentsdb:
  url: http://tsdb.rest.enn.cn:8080
  userKey: a0f5e2cb-3611-43cf-b4cc-11c2277e2bdd  #万能key

