#!/bin/sh
TARGET_NAME="energy_cloud.jar"
PROJECT_NAME="energy-provider-business"

cp -rf /app/docker /tmp
mvn clean package -pl ${PROJECT_NAME} -am -Dmaven.test.skip=true

cp  /app/${PROJECT_NAME}/target/${TARGET_NAME} /tmp/docker
ls /app/${PROJECT_NAME}/target
#--------------------------分割线------------------------------
ls /tmp/docker

