server:
  port: 8083

eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-01-fnw-release.topaas.enncloud.cn/eureka,http://eureka-02-fnw-release.topaas.enncloud.cn/eureka,http://eureka-03-fnw-release.topaas.enncloud.cn/eureka
    instance:
          lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
          lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
          instance-id: ${spring.cloud.client.ipAddress}:${server.port}  # 在信息列表时显示主机名称
          prefer-ip-address: true     # 访问的路径变为IP地址

auth:
  appid: 26f60f2bddfc4e0cacd99d6319cfba56
  appsecret: 086856a36b3941e3811a4d7de5fe70c1
  uac_url: https://uac.enncloud.cn

ribbon:
  ConnectTimeout: 1000000
  ReadTimeout: 600000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000

swagger:
  show: true

security:
  user:
    name: admin
    password: 1377a9f5b83e4aa5808cb5493bb590e8
  basic:
    path: /v2/api-docs,/monitoring

company:
  electric:
    count:
      day: 24
      month: 3
      year: 24
  steam:
    count:
      day: 31
      month: 12
      year: 1

#文件存储地址
file:
  domain: http://fnfs.pre.fanneng.com:8080/
  proplan: /group1/M00/00/28/CiceE1sDyZuAQ5cfAAArqTbCuXA76.xls

spring:
  redis:
    host:  10.39.48.242
    port: 6379
    database: 0
    password: FNpreadmin123
    timeout: 4000
    pool:
      max-active: 300
      min-idle: 10
      max-idle: 100
      max-wait: -1
      test-on-create: false
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true