spring:
  profiles:
   active: dev
  application:
    name: energy-consumer-web
  http:
    multipart:
      maxFileSize: 2Mb

feign:
  compression:
    request:
      mime-types:       # 可以被压缩的类型
      - text/xml
      - application/xml
      - application/json
      min-request-size: 2048 # 超过2048的字节进行压缩
logging:
  config: classpath:logback-web.xml